=== e21605352/minispec/xmlTest/minispec.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT system (entity*)>
    <!ATTLIST system name CDATA #REQUIRED >
<!ELEMENT entity (attribute*)>
    <!ATTLIST entity name CDATA #REQUIRED >
    
<!ELEMENT attribute (type) >
    <!ATTLIST attribute name CDATA #REQUIRED >
    
<!ELEMENT type (simpleType | collection) >
	
<!ELEMENT simpleType (#PCDATA) >
	<!ATTLIST simpleType type CDATA #REQUIRED >
	
<!ELEMENT collection (type) >
	<!ATTLIST  collection type (Set|Bag|Array|List) #REQUIRED >
	<!ATTLIST  collection size CDATA "1" >

=== e21605352/minispec/xmlTest/testClasseSimple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE system SYSTEM "minispec.dtd">
<system name="system">
	<entity name="Fourmisse">
		<attribute name="type">
			<type>
				<simpleType type="String" />
			</type>
		</attribute>
		<attribute name = "copains">
			<type>
				<collection type="List">
					<type>
						<collection type="Bag">
							<type>
								<simpleType type="Fourmisse" />
							</type>
						</collection>
					</type>
				</collection>
			</type>
		</attribute>
	</entity>
</system>

=== e21605352/minispec/xmlTest/testClasseSimple2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE system SYSTEM "minispec.dtd">
<system name="system">
	<entity name="Satellite">
		<attribute name="Nom" type="String" />
		<attribute name="Id" type="Integer" />
	</entity>
	<entity name="Balise">
		<attribute name="Nom" type="String" />
		<attribute name="Id" type="Integer" />
	</entity>
	<entity name="Fourmisse">
		<attribute name="type" type="String" />
		<attribute name="id" type="Integer" />
	</entity>
</system>
